version: '3.8'

# this is a development docker compose file.
# please, don't use it for production. It has exposed ports and default passwords.

services:
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: telegram_bot
    restart: "always"
    ports:
      - "8000:8000"
    depends_on:
      - telegram_bot_db
      - telegram_bot_redis
    env_file:
      - .env 
    volumes:
      - ./logs:/src/logs

  telegram_bot_db:
    image: postgres:16.1-alpine
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - telegram_bot_db:/var/lib/postgresql/data

  telegram_bot_redis:
    image: redis:7.2.4-alpine
    restart: "always"
    ports:
      - "6379:6379"

volumes:
  telegram_bot_db:
