version: '3.8'

services:
  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: "always"
    depends_on:
      - telegram_bot_db
      - telegram_bot_redis
    env_file:
      - app/configs/.env

  telegram_bot_db:
    image: postgres:16.1-alpine
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - telegram_bot_db:/var/lib/postgresql/data

  telegram_bot_redis:
    image: redis:7.2.4-alpine
    restart: "always"
    ports:
      - "6379:6379"


volumes:
  telegram_bot_db:
